/**
 * The onboarding wizard's shared brain: the configuration shape, its
 * validation, and THE script compiler.
 *
 * This module is imported by three runtimes that must never disagree:
 *
 *   1. the wizard UI       - instant preview plus an offline fallback,
 *   2. the /api/routers/generate-script handler - server compile + DB store,
 *   3. the tests that pin the generated bytes.
 *
 * The template is byte-for-byte the master deployment script the platform
 * documents - section comments and backslash continuations included - and
 * every {{PLACEHOLDER}} must resolve. A compile that would ship an unfilled
 * token THROWS instead: `{{RADIUS_SECRET}}` reaching a router is not a
 * cosmetic defect, the device would adopt the literal token as its shared
 * secret and fail RADIUS authentication silently forever after.
 */

export interface WizardConfig {
  // ── Step 1: basic router info ─────────────────────────────────────────────
  name: string
  model: string
  location: string
  // ── Step 2: interfaces & subnets ──────────────────────────────────────────
  /** Hotspot gateway in CIDR form. Default 10.5.50.1/24. */
  hotspotGw: string
  /** Default ether2. */
  hotspotInterface: string
  /** PPPoE gateway in CIDR form. Default 10.10.0.1/24. */
  pppoeGw: string
  /** Default ether3. */
  pppoeInterface: string
  /** Default login.ispflow.net. */
  hotspotDomain: string
  // ── Step 3: WireGuard & remote management ─────────────────────────────────
  wgPrivateKey: string
  wgPublicKey: string
  /** The router's tunnel address, e.g. 10.200.0.2/24. */
  wgAddress: string
  wgEndpointIp: string
  wgEndpointPort: number
  /** The platform's central peer key; falls back to the documented placeholder. */
  wgServerPubkey: string
  /** MANDATORY. The shared secret the RADIUS client is created with. */
  radiusSecret: string
  radiusServerIp: string
  /** Walled-garden bypass for the backend, derived from VITE_SUPABASE_URL. */
  supabaseApiHost: string
}

/** Every field a fresh wizard opens with - the spec's documented defaults. */
export function defaultWizardConfig(over: Partial<WizardConfig> = {}): WizardConfig {
  return {
    name: '', model: '', location: '',
    hotspotGw: '10.5.50.1/24',
    hotspotInterface: 'ether2',
    pppoeGw: '10.10.0.1/24',
    pppoeInterface: 'ether3',
    hotspotDomain: 'login.ispflow.net',
    wgPrivateKey: '', wgPublicKey: '',
    wgAddress: '10.200.0.2/24',
    wgEndpointIp: 'api.ispflow.net',
    wgEndpointPort: 51820,
    wgServerPubkey: '',
    radiusSecret: '',
    radiusServerIp: 'api.ispflow.net',
    supabaseApiHost: 'api.ispflow.net',
    ...over,
  }
}

const CIDR_RE = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\/(\d{1,2})$/
const IPV4_RE = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/

function octets(v: string): number[] | null {
  const m = (v.includes('/') ? CIDR_RE : IPV4_RE).exec(v.trim())
  if (!m) return null
  const parts = m.slice(1, 5).map(Number)
  return parts.some((o) => o > 255) ? null : parts
}

/** True for `10.5.50.1/24`-shaped input. */
export function isCidr(v: string): boolean {
  return CIDR_RE.test(v.trim()) && octets(v) !== null
}

/** True for a bare `10.5.50.1` IPv4 literal. */
export function isIpv4(v: string): boolean {
  return IPV4_RE.test(v.trim()) && octets(v) !== null
}

function toUint(v: string): { ip: number; prefix: number } {
  const parts = octets(v)
  if (!parts) throw new Error(`not an IPv4 CIDR: ${v}`)
  const prefix = Number(v.trim().split('/')[1] ?? '32')
  if (prefix > 32) throw new Error(`prefix out of range in: ${v}`)
  const ip = ((parts[0] * 2 ** 24) + (parts[1] * 2 ** 16) + (parts[2] * 2 ** 8) + parts[3]) >>> 0
  return { ip, prefix }
}

function toIp(n: number): string {
  const u = n >>> 0
  return [Math.floor(u / 2 ** 24) % 256, Math.floor(u / 2 ** 16) % 256,
    Math.floor(u / 2 ** 8) % 256, u % 256].join('.')
}

/** `10.5.50.1/24` -> `10.5.50.1` (the bare address for hotspot-address= etc). */
export function ipOf(cidr: string): string {
  return toIp(toUint(cidr).ip)
}

/** `10.5.50.1/24` -> `10.5.50.0/24` (the network the DHCP server hands out). */
export function subnetOf(cidr: string): string {
  const { ip, prefix } = toUint(cidr)
  const hosts = 2 ** (32 - prefix)
  return `${toIp(Math.floor(ip / hosts) * hosts)}/${prefix}`
}

/**
 * `10.5.50.1/24` -> `10.5.50.100-10.5.50.254`.
 *
 * For a /24 that is the conventional MikroTik dynamic range (upper third of
 * the subnet, gateway-safe). Smaller prefixes get a proportional slice so a
 * /29 still yields a usable pool instead of an empty one.
 */
export function poolOf(cidr: string): string {
  const { ip, prefix } = toUint(cidr)
  const hosts = 2 ** (32 - prefix)
  const net = Math.floor(ip / hosts) * hosts
  const bcast = net + hosts - 1
  const start = net + Math.max(2, Math.min(100, Math.floor(hosts / 2)))
  const end = Math.max(start, bcast - 1)
  return `${toIp(start)}-${toIp(end)}`
}

/** Appends `/24` to a bare address so the tunnel field accepts both shapes. */
export function ensureCidr(v: string): string {
  const t = v.trim()
  return t.includes('/') ? t : `${t}/24`
}

/**
 * Escapes a value for a double-quoted RouterOS string, so a quote or
 * backslash in a shared secret cannot close the literal and inject a second
 * command into a script that runs as root.
 */
export function rosEscape(v: string): string {
  return v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

// =============================================================================
//  THE MASTER TEMPLATE.
//
//  Byte-for-byte the structure the platform documents: nine numbered sections,
//  the banner, the trailing `/file print`, and the closing banner. Only the
//  {{PLACEHOLDER}} tokens are dynamic. The backslash-newline continuations are
//  RouterOS line joins and are part of the contract - the wizard tests pin
//  them, because a script that "mostly" matches the template is a script whose
//  placeholders nobody checked.
// =============================================================================
const TEMPLATE_PART_1 = `# ==============================================================================
# MASTER ISPFLOW CHR DEPLOYMENT SCRIPT (WIREGUARD + HOTSPOT + PPPOE + RADIUS)
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. WIREGUARD VPN SETUP (Remote Management & Backend Tunnel)
# ------------------------------------------------------------------------------
/interface wireguard remove [find name="wireguard-ispflow"]
/interface wireguard add name=wireguard-ispflow listen-port={{WG_ENDPOINT_PORT}} comment="ISPFlow Management Tunnel"

/ip address remove [find comment="WireGuard Tunnel IP"]
/ip address add address={{WG_ADDRESS}} interface=wireguard-ispflow comment="WireGuard Tunnel IP"

/interface wireguard peers remove [find comment~"ISPFlow"]
/interface wireguard peers add interface=wireguard-ispflow \\
    public-key="{{WG_SERVER_PUBKEY}}" \\
    allowed-address=10.200.0.0/24,10.0.0.0/8 \\
    endpoint-address="{{WG_ENDPOINT_IP}}" \\
    endpoint-port={{WG_ENDPOINT_PORT}} \\
    persistent-keepalive=25s \\
    comment="ISPFlow Central Server Peer"

# ------------------------------------------------------------------------------
# 2. NETWORK INTERFACES, IP ADDRESSES & POOLS
# ------------------------------------------------------------------------------
/ip address add address={{HOTSPOT_GW}} interface={{HOTSPOT_INTERFACE}} comment="Hotspot Gateway"
/ip address add address={{PPPOE_GW}} interface={{PPPOE_INTERFACE}} comment="PPPoE Gateway"

/ip pool add name=ispflow-hs-pool ranges={{HOTSPOT_POOL}}
/ip pool add name=ispflow-pppoe-pool ranges={{PPPOE_POOL}}

# ------------------------------------------------------------------------------
# 3. DHCP SERVER & DNS CONFIGURATION
# ------------------------------------------------------------------------------
/ip dhcp-server add name=dhcp-hotspot interface={{HOTSPOT_INTERFACE}} lease-time=1h address-pool=ispflow-hs-pool disabled=no
/ip dhcp-server network add address={{HOTSPOT_SUBNET}} gateway={{HOTSPOT_GW_IP}} dns-server={{HOTSPOT_GW_IP}},8.8.8.8,1.1.1.1 comment="Hotspot Network Setup"

/ip dns set allow-remote-requests=yes servers=8.8.8.8,1.1.1.1

`;
const TEMPLATE_PART_2 = `# ------------------------------------------------------------------------------
# 4. FIREWALL NAT & ROUTING
# ------------------------------------------------------------------------------
/ip firewall nat add chain=srcnat out-interface=ether1 action=masquerade comment="WAN Internet Nat"
/ip firewall nat add chain=srcnat out-interface=wireguard-ispflow action=masquerade comment="WireGuard Tunnel Nat"

/ip firewall filter add chain=input protocol=udp dst-port={{WG_ENDPOINT_PORT}} action=accept comment="Allow WireGuard Inbound"

# ------------------------------------------------------------------------------
# 5. HOTSPOT & CAPTIVE PORTAL PROFILE
# ------------------------------------------------------------------------------
/ip hotspot profile add name=ispflow-hs-profile \\
    hotspot-address={{HOTSPOT_GW_IP}} \\
    dns-name="{{HOTSPOT_DOMAIN}}" \\
    html-directory=hotspot \\
    login-by=http-chap,http-pap,mac-cookie \\
    mac-cookie-timeout=3d \\
    use-radius=yes

/ip hotspot add name=hs-{{HOTSPOT_INTERFACE}} interface={{HOTSPOT_INTERFACE}} address-pool=ispflow-hs-pool profile=ispflow-hs-profile disabled=no

# ------------------------------------------------------------------------------
# 6. WALLED GARDEN BYPASSES (M-Pesa, PayHero, GiftedPay, Supabase API)
# ------------------------------------------------------------------------------
/ip hotspot walled-garden
add dst-host="*.safaricom.co.ke" comment="M-Pesa Daraja API"
add dst-host="*.mpesa.co.ke" comment="M-Pesa Web"
add dst-host="*.payhero.co.ke" comment="PayHero Gateway"
add dst-host="*.giftedpay.com" comment="GiftedPay Gateway"
add dst-host="{{SUPABASE_API_HOST}}" comment="ISPFlow Backend API"
add dst-host="{{HOTSPOT_DOMAIN}}" comment="Hotspot Domain Bypass"

`;
const TEMPLATE_PART_3 = `# ------------------------------------------------------------------------------
# 7. PPPOE SERVER CONFIGURATION
# ------------------------------------------------------------------------------
/ppp profile add name="ispflow-pppoe-profile" local-address={{PPPOE_GW_IP}} remote-address=ispflow-pppoe-pool dns-server=8.8.8.8,1.1.1.1 use-ipv6=no use-mpls=no
/interface pppoe-server server add service-name="ispflow-pppoe" interface={{PPPOE_INTERFACE}} default-profile="ispflow-pppoe-profile" authentication=pap,chap disabled=no

# ------------------------------------------------------------------------------
# 8. RADIUS & COA (DISCONNECT REQUESTS)
# ------------------------------------------------------------------------------
/ppp aaa set use-radius=yes accounting=yes interim-update=5m
/user aaa set use-radius=yes

/radius incoming set accept=yes port=3799

/radius remove [find comment~"ISPFlow"]
/radius add service=hotspot,ppp address={{RADIUS_SERVER_IP}} secret="{{RADIUS_SECRET}}" timeout=3000ms authentication-port=1812 accounting-port=1813 comment="ISPFlow RADIUS Server"

# ------------------------------------------------------------------------------
# 9. ROUTER MANAGEMENT & API SERVICES
# ------------------------------------------------------------------------------
/ip service set [find name="api"] port=8728 disabled=no
/ip service set [find name="api-ssl"] port=8729 disabled=no
/ip service set [find name="winbox"] port=8291 disabled=no

/file print
# ==============================================================================
# DEPLOYMENT COMPLETE
# ==============================================================================
`;

/** The full template: every {{PLACEHOLDER}} below must be in the compiler map. */
export const SCRIPT_TEMPLATE = TEMPLATE_PART_1 + TEMPLATE_PART_2 + TEMPLATE_PART_3



