# These are supported funding model platforms
# github: [username]   # GitHub Sponsors
# patreon: username    # Patreon
# open_collective: ultrafaiba
# ko_fi: ultrafaiba
# liberapay: ultrafaiba
# issuehunt: ultrafaiba
# community_bridge: ultrafaiba
# tidelift: npm/isp-hotspot-billing
custom:
  - "https://www.buymeacoffee.com/ultrafaiba"
  - "https://paypal.me/ultrafaiba"
