# =============================================================================
# ISPFlow MikroTik Provisioning Script
# Generated by the ISPFlow RouterOS generator
# =============================================================================
# SAFETY:
# - WAN is excluded from the customer bridge automatically.
# - The router configuration is never reset by this script.
# - Existing unrelated router configuration is not deleted.
# - ISPFlow-owned objects are identified with comments.
# - Re-running this script is designed to be idempotent.
# =============================================================================

# -----------------------------------------------------------------------------
# 1. SYSTEM IDENTITY / TIME
# -----------------------------------------------------------------------------
/system identity set name="test-router"

# RouterOS 7 uses servers=; RouterOS 6 uses primary/secondary. The runtime
# version check keeps this single .rsc compatible with both families.
:if ([:pick [/system resource get version] 0 1] = "7") do={
    /system ntp client set enabled=yes servers=pool.ntp.org,time.google.com
} else={
    /system ntp client set enabled=yes primary-ntp="pool.ntp.org" secondary-ntp=time.google.com
};

:do { /system clock set time-zone-name="Africa/Nairobi" } on-error={
    :do { /system clock set time-zone-autodetect=yes } on-error={};
};

# -----------------------------------------------------------------------------
# 2. CUSTOMER BRIDGE — WAN-SAFE
# -----------------------------------------------------------------------------
# WAN selected: ether1
# Customer interfaces: ether2, wlan1
# WAN was not present in the customer bridge list.
:if ([:len [/interface bridge find where name="ispflow-hotspot"]] = 0) do={
    /interface bridge add name="ispflow-hotspot" comment="ISPFlow:customer-bridge"
};
:do { /interface bridge settings set [find bridge="ispflow-hotspot"] use-ip-firewall=yes } on-error={};

# Move ether2 into the ISPFlow customer bridge. WAN ether1 is never moved.
:do { /interface bridge port remove [find where interface="ether2"] } on-error={};
:if ([:len [/interface bridge port find where interface="ether2"]] = 0) do={
    /interface bridge port add interface="ether2" bridge="ispflow-hotspot" hw=no comment="ISPFlow:customer-port"
};

# Move wlan1 into the ISPFlow customer bridge. WAN ether1 is never moved.
:do { /interface bridge port remove [find where interface="wlan1"] } on-error={};
:if ([:len [/interface bridge port find where interface="wlan1"]] = 0) do={
    /interface bridge port add interface="wlan1" bridge="ispflow-hotspot" hw=no comment="ISPFlow:customer-port"
};

# -----------------------------------------------------------------------------
# 3. HOTSPOT GATEWAY / IP POOL / DHCP / DNS
# -----------------------------------------------------------------------------
:local ispflowItem [/ip address find where address="10.10.0.1/24"];
:if ([:len $ispflowItem] = 0) do={
    /ip address add address="10.10.0.1/24" interface="ispflow-hotspot" comment="ISPFlow:hotspot-gateway"
} else={
    /ip address set $ispflowItem interface="ispflow-hotspot" comment="ISPFlow:hotspot-gateway"
};
:if ([:len [/ip pool find where name="ispflow-hotspot-pool"]] = 0) do={
    /ip pool add name="ispflow-hotspot-pool" ranges="10.10.0.10-10.10.0.254" comment="ISPFlow:hotspot-pool"
};
/ip dns set servers=8.8.8.8,1.1.1.1 allow-remote-requests=yes
:if ([:len [/ip dhcp-server network find where comment="ISPFlow:hotspot-dhcp-network"]] = 0) do={
    /ip dhcp-server network add address="10.10.0.0/24" gateway="10.10.0.1" dns-server="10.10.0.1" comment="ISPFlow:hotspot-dhcp-network"
};
:if ([:len [/ip dhcp-server find where name="ispflow-hotspot-dhcp"]] = 0) do={
    /ip dhcp-server add name="ispflow-hotspot-dhcp" interface="ispflow-hotspot" address-pool="ispflow-hotspot-pool" lease-time=1h disabled=no comment="ISPFlow:hotspot-dhcp"
};

# DNS static entry keeps the captive portal hostname on the gateway.
:if ([:len [/ip dns static find where name="login.ispflow.net"]] = 0) do={
    /ip dns static add name="login.ispflow.net" address="10.10.0.1" comment="ISPFlow:captive-portal-dns"
};

# -----------------------------------------------------------------------------
# 4. WAN DHCP + NAT
# -----------------------------------------------------------------------------
:if ([:len [/ip dhcp-client find where interface="ether1"]] = 0) do={
    /ip dhcp-client add interface="ether1" disabled=no comment="ISPFlow:wan-dhcp"
};
:if ([:len [/ip firewall nat find where comment="ISPFlow:masquerade"]] = 0) do={
    /ip firewall nat add chain=srcnat action=masquerade out-interface="ether1" comment="ISPFlow:masquerade"
};

# -----------------------------------------------------------------------------
# 5. HOTSPOT
# -----------------------------------------------------------------------------
:local ispflowItem [/ip hotspot profile find where name="ispflow-hs-profile"];
:if ([:len $ispflowItem] = 0) do={
    /ip hotspot profile add name="ispflow-hs-profile" hotspot-address="10.10.0.1" dns-name="login.ispflow.net" html-directory=hotspot login-by=http-pap,http-chap,mac-cookie http-cookie-lifetime=1d use-radius=no comment="ISPFlow:hotspot-profile"
} else={
    /ip hotspot profile set $ispflowItem hotspot-address="10.10.0.1" dns-name="login.ispflow.net" html-directory=hotspot login-by=http-pap,http-chap,mac-cookie http-cookie-lifetime=1d use-radius=no comment="ISPFlow:hotspot-profile"
};
:local ispflowItem [/ip hotspot find where name="ispflow-hotspot"];
:if ([:len $ispflowItem] = 0) do={
    /ip hotspot add name="ispflow-hotspot" interface="ispflow-hotspot" address-pool="ispflow-hotspot-pool" profile="ispflow-hs-profile" disabled=no comment="ISPFlow:hotspot-server"
} else={
    /ip hotspot set $ispflowItem interface="ispflow-hotspot" address-pool="ispflow-hotspot-pool" profile="ispflow-hs-profile" disabled=no
};
:do { /ip hotspot ip-binding add address="10.10.0.1" type=bypassed comment="ISPFlow:gateway-bypass" } on-error={};

# HotSpot plan: 15 Mbps
:local ispflowItem [/ip hotspot user profile find where name="15-mbps"];
:if ([:len $ispflowItem] = 0) do={
    /ip hotspot user profile add name="15-mbps" rate-limit="5120k/15360k" shared-users=1 session-timeout=720:00:00 address-pool="ispflow-hotspot-pool" comment="ISPFlow:plan:hs-1"
} else={
    /ip hotspot user profile set $ispflowItem rate-limit="5120k/15360k" shared-users=1 session-timeout=720:00:00 address-pool="ispflow-hotspot-pool" comment="ISPFlow:plan:hs-1"
};

# -----------------------------------------------------------------------------
# 6. WALLED GARDEN / PRE-AUTH ACCESS
# -----------------------------------------------------------------------------
:if ([:len [/ip hotspot walled-garden find where dst-host="login.ispflow.net"]] = 0) do={
    /ip hotspot walled-garden add dst-host="login.ispflow.net" action=allow comment="ISPFlow:portal"
};
:if ([:len [/ip hotspot walled-garden find where dst-host="*.safaricom.co.ke"]] = 0) do={
    /ip hotspot walled-garden add dst-host="*.safaricom.co.ke" action=allow comment="ISPFlow:portal"
};
:if ([:len [/ip hotspot walled-garden find where dst-host="*.mpesa.co.ke"]] = 0) do={
    /ip hotspot walled-garden add dst-host="*.mpesa.co.ke" action=allow comment="ISPFlow:portal"
};
:if ([:len [/ip hotspot walled-garden find where dst-host="*.mpesa.in"]] = 0) do={
    /ip hotspot walled-garden add dst-host="*.mpesa.in" action=allow comment="ISPFlow:portal"
};
:if ([:len [/ip hotspot walled-garden find where dst-host="*.payhero.co.ke"]] = 0) do={
    /ip hotspot walled-garden add dst-host="*.payhero.co.ke" action=allow comment="ISPFlow:portal"
};
:if ([:len [/ip hotspot walled-garden find where dst-host="*.supabase.co"]] = 0) do={
    /ip hotspot walled-garden add dst-host="*.supabase.co" action=allow comment="ISPFlow:portal"
};
:do { /ip hotspot walled-garden ip add dst-address=0.0.0.0/0 protocol=udp dst-port=53 action=accept comment="ISPFlow:dns"; } on-error={};
:do { /ip hotspot walled-garden ip add dst-address=0.0.0.0/0 protocol=tcp dst-port=53 action=accept comment="ISPFlow:dns"; } on-error={};

# -----------------------------------------------------------------------------
# 7. PPPoE
# -----------------------------------------------------------------------------
# PPPoE service interface: ether3
:if ([:len [/ip pool find where name="ispflow-pppoe-pool"]] = 0) do={
    /ip pool add name="ispflow-pppoe-pool" ranges="10.20.0.2-10.20.3.254" comment="ISPFlow:pppoe-pool"
};
:local ispflowItem [/ppp profile find where name="ispflow-pppoe-profile"];
:if ([:len $ispflowItem] = 0) do={
    /ppp profile add name="ispflow-pppoe-profile" local-address="10.20.0.1" remote-address="ispflow-pppoe-pool" dns-server="10.20.0.1" use-ipv6=no comment="ISPFlow:pppoe-profile"
} else={
    /ppp profile set $ispflowItem local-address="10.20.0.1" remote-address="ispflow-pppoe-pool" dns-server="10.20.0.1" use-ipv6=no comment="ISPFlow:pppoe-profile"
};
:local ispflowItem [/interface pppoe-server server find where service-name="ispflow-pppoe"];
:if ([:len $ispflowItem] = 0) do={
    /interface pppoe-server server add service-name="ispflow-pppoe" interface="ether3" default-profile="ispflow-pppoe-profile" authentication=pap,chap disabled=no comment="ISPFlow:pppoe-server"
} else={
    /interface pppoe-server server set $ispflowItem interface="ether3" default-profile="ispflow-pppoe-profile" disabled=no
};

# -----------------------------------------------------------------------------
# 9. SAFE FIREWALL BASELINE
# -----------------------------------------------------------------------------
# Deliberately no blanket DROP rule: this generator must not lock the operator out.
:if ([:len [/ip firewall filter find where comment="ISPFlow:established"]] = 0) do={
    /ip firewall filter add chain=input connection-state=established,related action=accept comment="ISPFlow:established"
};
:if ([:len [/ip firewall filter find where comment="ISPFlow:icmp"]] = 0) do={
    /ip firewall filter add chain=input protocol=icmp action=accept comment="ISPFlow:icmp"
};
:if ([:len [/ip firewall filter find where comment="ISPFlow:dhcp"]] = 0) do={
    /ip firewall filter add chain=input in-interface="ispflow-hotspot" protocol=udp dst-port=67-68 action=accept comment="ISPFlow:dhcp"
};
:if ([:len [/ip firewall filter find where comment="ISPFlow:dns"]] = 0) do={
    /ip firewall filter add chain=input in-interface="ispflow-hotspot" protocol=udp dst-port=53 action=accept comment="ISPFlow:dns"
};
:if ([:len [/ip firewall filter find where comment="ISPFlow:api-lan"]] = 0) do={
    /ip firewall filter add chain=input in-interface="ispflow-hotspot" protocol=tcp dst-port=8728,8729 action=accept comment="ISPFlow:api-lan"
};
:if ([:len [/ip firewall filter find where comment="ISPFlow:api-wan-drop"]] = 0) do={
    /ip firewall filter add chain=input in-interface="ether1" protocol=tcp dst-port=8728,8729 action=drop comment="ISPFlow:api-wan-drop"
};

# -----------------------------------------------------------------------------
# 10. GLOBAL HOTSPOT QUEUE
# -----------------------------------------------------------------------------
:if ([:len [/queue simple find where comment="ISPFlow:hotspot-global"]] = 0) do={
    /queue simple add name="ISPFlow-HotSpot-Global" target="10.10.0.0/24" max-limit=100M/100M comment="ISPFlow:hotspot-global"
};

# -----------------------------------------------------------------------------
# 11. MANAGEMENT API
# -----------------------------------------------------------------------------
:do { /ip service set [find name="api"] disabled=no port=8728 } on-error={};
:do { /ip service set [find name="api-ssl"] disabled=no port=8729 } on-error={};

# -----------------------------------------------------------------------------
# 12. OPTIONAL ADMIN PASSWORD
# -----------------------------------------------------------------------------
# The UI default is blank. A password is only changed when the operator explicitly enters one.
# No admin password was supplied; existing credentials are untouched.

# -----------------------------------------------------------------------------
# 13. VERIFICATION
# -----------------------------------------------------------------------------
/system resource print
/interface print
/interface bridge print where name="ispflow-hotspot"
/ip address print where interface="ispflow-hotspot"
/ip route print where dst-address=0.0.0.0/0
/ip dhcp-server print where name="ispflow-hotspot-dhcp"
/ip hotspot print where name="ispflow-hotspot"
/interface pppoe-server server print where service-name="ispflow-pppoe"

# =============================================================================
# ISPFlow PROVISIONING COMPLETE
# =============================================================================
# WAN: ether1
# HotSpot bridge: ispflow-hotspot
# HotSpot clients: ether2, wlan1
# HotSpot gateway: 10.10.0.1/24
# PPPoE: ether3
# Plans: 1
# =============================================================================
