"""Migration FK fixer

Safe, idempotent tool to move inline sa.ForeignKeyConstraint(...) entries
out of op.create_table(...) blocks into deferred op.create_foreign_key(...) calls
at the end of the migration file, and to add corresponding op.drop_constraint(...)
lines to the downgrade. Intended for use in dev and production repositories to
quickly resolve circular FK ordering issues in migration files.

Usage:
    python scripts/tools/migration_fk_fixer.py <migration_file> [--apply]

If run without --apply, prints a diff summary and exits. With --apply it updates
the file (backing up a .bak file first). The tool is idempotent.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path
from typing import List, Tuple

FK_INLINER = re.compile(r"\s*sa\.ForeignKeyConstraint\(\[(?P<local>[^\]]+)\], \['(?P<refer>[^']+)'\], name=op\.f\('(?P<name>[^']+)'\)(?:,\s*ondelete=\s*'(?P<ondelete>[^']+)')?\),?,?\s*\n")
CREATE_TABLE_RE = re.compile(r"\s*op\.create_table\('\s*(?P<table>[^']+)'")
END_MARKER = "# ### end Alembic commands ###"
DOWGRADE_HEADER = "def downgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###"


def parse_migration(path: Path) -> Tuple[str, List[Tuple[str, str, List[str], str, List[str], str]]]:
    text = path.read_text(encoding='utf-8')
    lines = text.splitlines(keepends=True)
    new_lines = []
    found = []  # tuples: (constraint_name, source_table, local_cols, refer_table, refer_cols, ondelete)
    current_table: str | None = None

    for ln in lines:
        m = CREATE_TABLE_RE.match(ln)
        if m:
            current_table = m.group('table')
            new_lines.append(ln)
            continue

        m2 = FK_INLINER.match(ln)
        if m2 and current_table:
            local = m2.group('local').strip()
            local_cols = [c.strip().strip("'\"") for c in local.split(',') if c.strip()]
            refer = m2.group('refer')
            if '.' in refer:
                refer_table, refer_col = refer.split('.')
            else:
                refer_table, refer_col = refer, 'id'
            name = m2.group('name')
            ondelete = m2.group('ondelete') or 'SET NULL'
            found.append((name, current_table, local_cols, refer_table, [refer_col], ondelete))
            new_lines.append(f"    # Deferred FK moved to bottom: {name} -> {refer}\n")
            continue

        new_lines.append(ln)

    return ''.join(new_lines), found


def build_deferred_block(found: List[Tuple[str, str, List[str], str, List[str], str]]) -> str:
    if not found:
        return ''
    lines: List[str] = []
    lines.append('\n    # ### Deferred foreign keys moved to end to avoid circular/ordering issues ###\n')
    for name, src, local_cols, ref_table, ref_cols, ondelete in found:
        local_repr = '[' + ', '.join([f"'{c}'" for c in local_cols]) + ']'
        ref_repr = '[' + ', '.join([f"'{c}'" for c in ref_cols]) + ']'
        lines.append(f"    op.create_foreign_key(op.f('{name}'), '{src}', '{ref_table}', {local_repr}, {ref_repr}, ondelete='{ondelete}')\n")
    return ''.join(lines)


def build_drop_block(found: List[Tuple[str, str, List[str], str, List[str], str]]) -> str:
    if not found:
        return ''
    lines: List[str] = []
    for name, src, *_ in found:
        lines.append(f"    op.drop_constraint(op.f('{name}'), '{src}', type_='foreignkey')\n")
    return ''.join(lines)


def apply_fix(path: Path, apply: bool = False) -> int:
    text = path.read_text(encoding='utf-8')
    new_text, found = parse_migration(path)
    if not found:
        print(f"No inline FK constraints found in {path}")
        return 0

    deferred = build_deferred_block(found)
    drop_block = build_drop_block(found)

    # Insert deferred block before END_MARKER (if present)
    if END_MARKER in new_text:
        if deferred.strip():
            new_text = new_text.replace(END_MARKER, deferred + '\n    ' + END_MARKER)
    else:
        new_text = new_text + '\n' + deferred

    # Insert drop_block after downgrade header
    if DOWGRADE_HEADER in new_text:
        new_text = new_text.replace(DOWGRADE_HEADER, DOWGRADE_HEADER + '\n' + drop_block)
    else:
        print('WARNING: downgrade header not found - skipping drop additions')

    if apply:
        bak = path.with_suffix(path.suffix + '.bak')
        bak.write_text(text, encoding='utf-8')
        path.write_text(new_text, encoding='utf-8')
        print(f'Applied fixes to {path} (backed up to {bak}). Moved {len(found)} FKs to deferred block.')
    else:
        print(f'Found {len(found)} inline FK constraints in {path}. Run with --apply to modify file.')
    return len(found)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Move inline FK constraints out of migration files (idempotent)')
    parser.add_argument('path', type=str, help='Path to migration file or directory (alembic/versions)')
    parser.add_argument('--apply', action='store_true', help='Apply changes')
    args = parser.parse_args()

    p = Path(args.path)
    targets: List[Path] = []
    if p.is_dir():
        targets = sorted([x for x in p.glob('*.py') if x.is_file()])
    else:
        targets = [p]

    total = 0
    for t in targets:
        total += apply_fix(t, apply=args.apply)

    print(f'Total moved FK constraints: {total}')